name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e ".[dev]"
        
    - name: Setup Oracle Client
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y libaio-dev unzip
        sudo mkdir -p /opt/oracle
        cd /opt/oracle
        wget https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basic-linux.x64-23.7.0.25.01.zip
        unzip instantclient-basic-linux.x64-23.7.0.25.01.zip
        sudo sh -c "echo /opt/oracle/instantclient_23_7 > /etc/ld.so.conf.d/oracle-instantclient.conf"
        sudo ldconfig
        echo "ORACLE_HOME=/opt/oracle/instantclient_23_7" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_23_7:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        
    - name: Setup Oracle Network Configuration
      run: |
        sudo mkdir -p /opt/oracle/network/admin
        sudo cp .github/workflows/tnsnames.ora /opt/oracle/network/admin/
        sudo chmod 644 /opt/oracle/network/admin/tnsnames.ora
        sudo ln -s /opt/oracle/network/admin /opt/oracle/instantclient_23_7/network/admin
        echo "TNS_ADMIN=/opt/oracle/network/admin" >> $GITHUB_ENV

    - name: Run tests
      env:
        PYTHONPATH: ${PYTHONPATH}:${GITHUB_WORKSPACE}/src
        ORACLE_USER: dummy
        ORACLE_PASSWORD: dummy123
        ORACLE_SERVICE: ORCLCDB
        ORACLE_HOST: localhost
        ORACLE_PORT: 1521
        TNS_ADMIN: /opt/oracle/network/admin
      run: |
        python -m pytest tests/ --cov=src --cov-report=xml -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        
    - name: Check formatting
      run: |
        black --check src/ tests/
        isort --check-only src/ tests/
        
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=100 src/ tests/
        
  docker:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: adityasugandhi/oracle-mcp:latest