name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mcp
        pip install -e ".[dev]"
        
    - name: Run tests
      env:
        PYTHONPATH: ${PYTHONPATH}:${GITHUB_WORKSPACE}/src
        # Use dummy values for testing - tests will skip Oracle-specific tests
        ORACLE_USER: dummy
        ORACLE_PASSWORD: dummy
        ORACLE_DSN: dummy
      run: |
        python -m pytest tests/ --cov=src --cov-report=xml -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        
    - name: Check formatting
      run: |
        black --check src/ tests/
        isort --check-only src/ tests/
        
    - name: Lint with flake8
      run: |
        flake8 src/ tests/
        
    - name: Type check with mypy
      run: |
        mypy src/ tests/

  docker:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: adityasugandhi/oracle-mcp:latest